#!/usr/bin/env node
/**
 * gen-closure — generates and verifies the WARRANTED SCOPE of angulux.
 *
 * Why it exists: the seed set is the list of modules an application imports DIRECTLY. That
 * is a seed, not a maintenance unit. Running BFS over the internal dependency graph pulls
 * in roughly twenty more infrastructure modules — `paginator`, `scroller`, `overlay`,
 * `focustrap`, `types` among them. Warranting only the seed set would put a bug in
 * `scroller` outside the warranty while it breaks the data table, which is the heaviest
 * thing most applications use.
 *
 * The resulting number is the SINGLE SOURCE OF TRUTH for the project's scope: generated by
 * machine, committed to the repo. Any drift between it and the number of built entrypoints
 * is a defect, not a rounding difference.
 *
 * Usage:
 *   node tools/scope/gen-closure.mjs              # sinh closure.json
 *   node tools/scope/gen-closure.mjs --check      # verify only, no writes (for CI)
 *   node tools/scope/gen-closure.mjs --src <dir>  # point at a source directory
 */

import fs from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const srcArg = args.indexOf('--src') >= 0 ? args[args.indexOf('--src') + 1] : null;

const root = process.cwd();
const OUT = path.join(root, 'tools/scope/closure.json');

/** The modules that consuming applications import directly — measured, not guessed. */
const SEEDS = [
    'api', 'avatar', 'avatargroup', 'badge', 'button', 'card', 'chart', 'checkbox', 'chip',
    'colorpicker', 'config', 'confirmdialog', 'datepicker', 'dialog', 'divider', 'drawer',
    'fileupload', 'iconfield', 'inputicon', 'inputnumber', 'inputtext', 'menu', 'message',
    'multiselect', 'password', 'popover', 'progressbar', 'progressspinner', 'radiobutton',
    'ripple', 'select', 'selectbutton', 'skeleton', 'splitbutton', 'table', 'tabs', 'tag',
    'textarea', 'timeline', 'toast', 'toggleswitch', 'tooltip', 'treetable'
];

function resolveSrc() {
    if (srcArg) return path.resolve(srcArg);
    const own = path.join(root, 'packages/angulux/src');
    if (fs.existsSync(own)) return own;
    const ref = path.join(root, 'ref/primeng/packages/primeng/src');
    if (fs.existsSync(ref)) return ref;
    console.error('✗ Source directory not found. Pass --src <dir>.');
    process.exit(1);
}

const SRC = resolveSrc();
const dirs = new Set(fs.readdirSync(SRC).filter((d) => fs.statSync(path.join(SRC, d)).isDirectory()));

/** Scan every import in a module and reduce it to sibling directory names. */
function depsOf(dir) {
    const out = new Set();
    const walk = (d) => {
        for (const e of fs.readdirSync(d, { withFileTypes: true })) {
            const p = path.join(d, e.name);
            if (e.isDirectory()) { walk(p); continue; }
            if (!e.name.endsWith('.ts') || e.name.endsWith('.spec.ts')) continue;
            const t = fs.readFileSync(p, 'utf8');
            // package-style import: 'primeng/<mod>' or 'angulux/<mod>'
            for (const m of t.matchAll(/from\s+['"](?:primeng|angulux)\/([a-z0-9-]+)/g)) out.add(m[1]);
            // relative import climbing into a sibling module: '../../<mod>'
            for (const m of t.matchAll(/from\s+['"](?:\.\.\/)+([a-z0-9-]+)(?:\/|['"])/g)) out.add(m[1]);
        }
    };
    walk(path.join(SRC, dir));
    const res = new Set();
    for (const d of out) if (dirs.has(d) && d !== dir) res.add(d);
    return res;
}

const graph = {};
for (const d of dirs) graph[d] = depsOf(d);

// --- BFS tu seeds ---
const closure = new Set();
const stack = SEEDS.filter((s) => dirs.has(s));
const missingSeeds = SEEDS.filter((s) => !dirs.has(s));
while (stack.length) {
    const n = stack.pop();
    if (closure.has(n)) continue;
    closure.add(n);
    for (const d of graph[n]) if (!closure.has(d)) stack.push(d);
}

const inScope = [...closure].sort();
const outOfScope = [...dirs].filter((d) => !closure.has(d)).sort();
const infra = inScope.filter((d) => !SEEDS.includes(d));

// --- Check: no import from INSIDE the set may point OUTSIDE the set ---
const leaks = [];
for (const d of inScope) {
    for (const dep of graph[d]) {
        if (!closure.has(dep)) leaks.push(`${d} -> ${dep}`);
    }
}

const payload = {
    _comment: 'GENERATED — do not edit by hand. Source: tools/scope/gen-closure.mjs',
    generatedFrom: path.relative(root, SRC),
    seedCount: SEEDS.length,
    closureCount: inScope.length,
    outOfScopeCount: outOfScope.length,
    seeds: SEEDS,
    infrastructurePulledIn: infra,
    closure: inScope,
    outOfScope
};

console.log(`  source            : ${path.relative(root, SRC)}`);
console.log(`  tong thu muc      : ${dirs.size}`);
console.log(`  seed (direct imports) : ${SEEDS.length}${missingSeeds.length ? `  ⚠ not found: ${missingSeeds.join(', ')}` : ''}`);
console.log(`  CLOSURE (warranted)   : ${inScope.length}`);
console.log(`  pulled-in infra       : ${infra.length} -> ${infra.join(' ')}`);
console.log(`  out of scope          : ${outOfScope.length}`);

let bad = false;

if (missingSeeds.length) {
    console.error(`\n✗ Seed module missing from source: ${missingSeeds.join(', ')}`);
    bad = true;
}
if (leaks.length) {
    console.error(`\n✗ ${leaks.length} import(s) point from INSIDE the closure to OUTSIDE it:`);
    for (const l of leaks.slice(0, 20)) console.error(`   ${l}`);
    bad = true;
}

if (CHECK) {
    if (!fs.existsSync(OUT)) {
        console.error('\n✗ tools/scope/closure.json does not exist yet — run without --check to generate it.');
        process.exit(1);
    }
    const prev = JSON.parse(fs.readFileSync(OUT, 'utf8'));
    if (JSON.stringify(prev.closure) !== JSON.stringify(inScope)) {
        console.error('\n✗ The closure has DRIFTED from the committed closure.json.');
        const added = inScope.filter((x) => !prev.closure.includes(x));
        const removed = prev.closure.filter((x) => !inScope.includes(x));
        if (added.length) console.error(`   them: ${added.join(', ')}`);
        if (removed.length) console.error(`   mat : ${removed.join(', ')}`);
        console.error('   If the change is intentional, re-run without --check and commit the result.');
        bad = true;
    }
    if (bad) process.exit(1);
    console.log('\n✓ gen-closure --check: scope matches the committed closure.json, no leakage.');
} else {
    if (bad) process.exit(1);
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, JSON.stringify(payload, null, 4) + '\n');
    console.log(`\n✓ da ghi ${path.relative(root, OUT)}`);
}
