/**
 * The PrimeNG -> angulux selector map.
 *
 * GENERATED from `tools/codemod/selectors.json`, the same allowlist the library's own
 * rename used. It is committed rather than read at run time because this package ships
 * standalone: someone running `npx angulux-migrate` has no copy of this repository.
 * `test/selector-map.test.mjs` re-derives it from the source and fails if the two drift.
 *
 * The rename was an ALLOWLIST, never a `p-` -> `agl-` pattern. That distinction is the
 * whole safety property: a pattern would also rewrite `p-` tokens that are not selectors,
 * and a project's own `p-something` component would be renamed out from under it.
 */

/** Element selectors: `p-button` -> `agl-button` (115). */
export const ELEMENTS = {
    'p-avatar': 'agl-avatar',
    'p-avatar-group': 'agl-avatar-group',
    'p-avatarGroup': 'agl-avatarGroup',
    'p-avatargroup': 'agl-avatargroup',
    'p-badge': 'agl-badge',
    'p-button': 'agl-button',
    'p-card': 'agl-card',
    'p-cellEditor': 'agl-cellEditor',
    'p-chart': 'agl-chart',
    'p-check-box': 'agl-check-box',
    'p-checkBox': 'agl-checkBox',
    'p-checkbox': 'agl-checkbox',
    'p-chip': 'agl-chip',
    'p-color-picker': 'agl-color-picker',
    'p-colorPicker': 'agl-colorPicker',
    'p-colorpicker': 'agl-colorpicker',
    'p-column-filter': 'agl-column-filter',
    'p-columnFilter': 'agl-columnFilter',
    'p-columnFilterFormElement': 'agl-columnFilterFormElement',
    'p-columnfilter': 'agl-columnfilter',
    'p-confirm-dialog': 'agl-confirm-dialog',
    'p-confirmDialog': 'agl-confirmDialog',
    'p-confirmdialog': 'agl-confirmdialog',
    'p-date-picker': 'agl-date-picker',
    'p-datePicker': 'agl-datePicker',
    'p-datepicker': 'agl-datepicker',
    'p-dialog': 'agl-dialog',
    'p-divider': 'agl-divider',
    'p-drawer': 'agl-drawer',
    'p-fileUpload': 'agl-fileUpload',
    'p-fileupload': 'agl-fileupload',
    'p-fluid': 'agl-fluid',
    'p-footer': 'agl-footer',
    'p-header': 'agl-header',
    'p-icon-field': 'agl-icon-field',
    'p-iconField': 'agl-iconField',
    'p-iconfield': 'agl-iconfield',
    'p-input-number': 'agl-input-number',
    'p-inputIcon': 'agl-inputIcon',
    'p-inputNumber': 'agl-inputNumber',
    'p-inputicon': 'agl-inputicon',
    'p-inputnumber': 'agl-inputnumber',
    'p-menu': 'agl-menu',
    'p-message': 'agl-message',
    'p-motion': 'agl-motion',
    'p-multi-select': 'agl-multi-select',
    'p-multiSelect': 'agl-multiSelect',
    'p-multiselect': 'agl-multiselect',
    'p-overlay': 'agl-overlay',
    'p-paginator': 'agl-paginator',
    'p-password': 'agl-password',
    'p-popover': 'agl-popover',
    'p-progress-bar': 'agl-progress-bar',
    'p-progress-spinner': 'agl-progress-spinner',
    'p-progressBar': 'agl-progressBar',
    'p-progressSpinner': 'agl-progressSpinner',
    'p-progressbar': 'agl-progressbar',
    'p-progressspinner': 'agl-progressspinner',
    'p-radio-button': 'agl-radio-button',
    'p-radioButton': 'agl-radioButton',
    'p-radiobutton': 'agl-radiobutton',
    'p-scroller': 'agl-scroller',
    'p-select': 'agl-select',
    'p-select-button': 'agl-select-button',
    'p-selectButton': 'agl-selectButton',
    'p-selectItem': 'agl-selectItem',
    'p-selectbutton': 'agl-selectbutton',
    'p-skeleton': 'agl-skeleton',
    'p-sortIcon': 'agl-sortIcon',
    'p-split-button': 'agl-split-button',
    'p-splitButton': 'agl-splitButton',
    'p-splitbutton': 'agl-splitbutton',
    'p-tab': 'agl-tab',
    'p-table': 'agl-table',
    'p-tableCheckbox': 'agl-tableCheckbox',
    'p-tableHeaderCheckbox': 'agl-tableHeaderCheckbox',
    'p-tableRadioButton': 'agl-tableRadioButton',
    'p-tablist': 'agl-tablist',
    'p-tabpanel': 'agl-tabpanel',
    'p-tabpanels': 'agl-tabpanels',
    'p-tabs': 'agl-tabs',
    'p-tag': 'agl-tag',
    'p-tiered-menu': 'agl-tiered-menu',
    'p-tieredMenu': 'agl-tieredMenu',
    'p-tieredMenuSub': 'agl-tieredMenuSub',
    'p-tieredmenu': 'agl-tieredmenu',
    'p-tieredmenusub': 'agl-tieredmenusub',
    'p-timeline': 'agl-timeline',
    'p-toast': 'agl-toast',
    'p-toastItem': 'agl-toastItem',
    'p-toggle-button': 'agl-toggle-button',
    'p-toggle-switch': 'agl-toggle-switch',
    'p-toggleButton': 'agl-toggleButton',
    'p-toggleSwitch': 'agl-toggleSwitch',
    'p-togglebutton': 'agl-togglebutton',
    'p-toggleswitch': 'agl-toggleswitch',
    'p-tree-table': 'agl-tree-table',
    'p-tree-table-checkbox': 'agl-tree-table-checkbox',
    'p-tree-table-sort-icon': 'agl-tree-table-sort-icon',
    'p-treeTable': 'agl-treeTable',
    'p-treeTableCellEditor': 'agl-treeTableCellEditor',
    'p-treeTableCheckbox': 'agl-treeTableCheckbox',
    'p-treeTableHeaderCheckbox': 'agl-treeTableHeaderCheckbox',
    'p-treeTableSortIcon': 'agl-treeTableSortIcon',
    'p-treeTableToggler': 'agl-treeTableToggler',
    'p-treetable': 'agl-treetable',
    'p-treetable-cell-editor': 'agl-treetable-cell-editor',
    'p-treetable-checkbox': 'agl-treetable-checkbox',
    'p-treetable-sort-icon': 'agl-treetable-sort-icon',
    'p-treetable-toggler': 'agl-treetable-toggler',
    'p-treetablecelleditor': 'agl-treetablecelleditor',
    'p-treetabletoggler': 'agl-treetabletoggler',
    'p-virtual-scroller': 'agl-virtual-scroller',
    'p-virtualScroller': 'agl-virtualScroller',
    'p-virtualscroller': 'agl-virtualscroller'
};

/** Attribute selectors / directives: `pButton` -> `aglButton` (35). */
export const ATTRIBUTES = {
    'pAutoFocus': 'aglAutoFocus',
    'pBadge': 'aglBadge',
    'pBind': 'aglBind',
    'pButton': 'aglButton',
    'pButtonIcon': 'aglButtonIcon',
    'pButtonLabel': 'aglButtonLabel',
    'pCancelEditableRow': 'aglCancelEditableRow',
    'pContextMenuRow': 'aglContextMenuRow',
    'pEditableColumn': 'aglEditableColumn',
    'pEditableRow': 'aglEditableRow',
    'pFileContent': 'aglFileContent',
    'pFocusTrap': 'aglFocusTrap',
    'pFrozenColumn': 'aglFrozenColumn',
    'pInitEditableRow': 'aglInitEditableRow',
    'pInputText': 'aglInputText',
    'pInputTextarea': 'aglInputTextarea',
    'pMenuItemContent': 'aglMenuItemContent',
    'pMotion': 'aglMotion',
    'pPassword': 'aglPassword',
    'pReorderableColumn': 'aglReorderableColumn',
    'pReorderableRow': 'aglReorderableRow',
    'pReorderableRowHandle': 'aglReorderableRowHandle',
    'pResizableColumn': 'aglResizableColumn',
    'pRipple': 'aglRipple',
    'pRowGroupHeader': 'aglRowGroupHeader',
    'pRowToggler': 'aglRowToggler',
    'pSaveEditableRow': 'aglSaveEditableRow',
    'pSelectableRow': 'aglSelectableRow',
    'pSelectableRowDblClick': 'aglSelectableRowDblClick',
    'pSortableColumn': 'aglSortableColumn',
    'pTableBody': 'aglTableBody',
    'pTemplate': 'aglTemplate',
    'pTextarea': 'aglTextarea',
    'pTooltip': 'aglTooltip',
    'pTreeTableBody': 'aglTreeTableBody'
};

/** Import specifier rewrite. The target is SCOPED — the bare name does not resolve on npm. */
export const IMPORT_FROM = 'primeng';
export const IMPORT_TO = '@anguless/angulux';
